-- ============================================
-- CORREÇÃO: Desabilitar RLS nas tabelas
-- ============================================
-- ATENÇÃO: Prefira usar supabase-rls-policies.sql
-- para habilitar RLS com políticas adequadas.
-- 
-- Descomente as linhas abaixo APENAS se as
-- políticas de RLS estiverem bloqueando o app:

-- ALTER TABLE users DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE questions DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE performance DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE error_notebook DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_comments DISABLE ROW LEVEL SECURITY;

-- ============================================
-- IMPORTANTE:
-- As funções RPC (supabase-rpc-functions.sql)
-- usam SECURITY DEFINER, então funcionam mesmo
-- com RLS habilitado.
-- 
-- Recomendado: execute supabase-rls-policies.sql
-- em vez de desabilitar RLS.
-- ============================================
